# Use official Python image
FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/server

# Expose port
EXPOSE 5000

# Run the FastAPI server as a module
CMD ["python", "-m", "server.server"]
